### PR TITLE
Deliver downlink messages to (callback) function

### PR DESCRIPTION
**Pull request by Nicolasdejean**
created onMessage() to clarify sendBytes.
onMessage() contains a buffer downlink and an int downlinkPort to get info on the received message and then send the info to receiveEvent().#23
I couldn't register onMessage() like an event: it needs libraries like <event.h> and <wire.h>, so the user can't choose what to put in onMessage().
I added some (not the right ones) return values for sendBytes.#11

### CODE REVIEW

**Comment by FokkeZB** [comment]
@Nicolasdejean could you give an example of a downlink Sketch? Don't quite get how this would look to the user now, confused by the header `int onMessage(string response)`.

**Comment by Nicolasdejean** [comment]
@FokkeZB The user won't see ttn.onMessage I know it's not user friendly, so I'm trying to see if I can do something so that the user can understand the code that we are giving him.
```
#define DEBUG 1
#include <TheThingsNetwork.h>

// Set your AppEUI and AppKey
const byte appEui[8] = { 0x70, 0xB3, 0xD5, 0x7E, 0xD0, 0x00, 0x0D, 0x35 };
const byte appKey[16] = { 0x34, 0xB8, 0x07, 0x01, 0xAB, 0x87, 0x05, 0x38, 0x34, 0xFB, 0x5C, 0x68, 0x6D, 0x6B, 0xED, 0xF6 };

#define debugSerial Serial
#define loraSerial Serial1

fp_ttn_t fp = 0;
TheThingsNetwork ttn(fp);

void setup()
{
  debugSerial.begin(115200);
  loraSerial.begin(57600);
  ttn.init(loraSerial, debugSerial);
  
  // the device will attempt a join every 10 seconds till the join is successfull
  ttn.join(appEui, appKey, true, 10000, 1000);
  ttn.showStatus();
  debugSerialPrintLn("Setup for The Things Network complete");
}

void loop() {
 ttn.poll(); /* contains sendbytes() that calls onMessage() if it receives a message */
 delay(20000);
}

void receiveEvent(const byte* buffer, int length, int port) /* onMessage() calls receiveEvent() */
{
  debugSerialPrint("Receive" + String(length) + " bytes on port " + String(port) + ":");
  for (int i = 0; i < length; i++)
    debugSerialPrint(String(buffer[i]) + " ");
  debugSerialPrintLn();
}
```

**Comment by FokkeZB** [comment]
I think this is an improvement already since sending and retrieving is now separated and you get all information (buffer, length and port) in one go.

Just to clarify, it's not possible that the user defines what function should be called? For example in `setup()` he would say:

```c
ttn.onMessage(receiveEvent);
```

If that is not possible, then we just have to document `receiveEvent` as convention. I'd suggest to rename it to `message`or `onMessage` to be more aligned to the application libraries.

**Comment by FokkeZB** [comment]
I found a way to let the user define the callback: #43

**Comment by FokkeZB** [comment]
Closing for #43

**Pull request closed without merging**
