### PR TITLE
update CayenneLPP docs link

### PR DESCRIPTION
**Pull request by asanchezdelc**
We recently made a few changes to our docs page, so this change is reflecting that.

### CODE REVIEW

**Comment by jpmeijers** [comment]
LGTM

I see in your docs you refer to **Cayenne Low Power Payload (LPP)**, while we talk about **Cayenne Lower Power Protocol (LPP)**. I take it that we should update that too.

**Comment by johanstokking** [comment]
@asanchezdelc can you sign CLA and update to using Low Power Payload?

**Comment by asanchezdelc** [comment]
@johanstokking done.

**Comment by johanstokking** [comment]
Thanks!

**Pull request merged**
