### PR TITLE
Re-enable test, ignore parentheses

### PR DESCRIPTION
**Pull request by FokkeZB**
**DO NOT MERGE**

Not all of #119 is resolved yet.

### CODE REVIEW

**Comment by FokkeZB** [comment]
I'll not merge this yet. Will have to fix some other issues of #121 first

**Comment by FokkeZB** [comment]
Once #144 is merged after https://github.com/TheThingsNetwork/arduino-device-lib/pull/144#pullrequestreview-10230729 has been addressed, this PR should be rebased and merged so that we have CI in place. We can than address the other points from #119 once we get to merge #135.

**Comment by johanstokking** [comment]
OK, then close the PR and reopen once it's ready to merge.

**Comment by FokkeZB** [comment]
Once #145 is fixed, this PR can be (rebased and) merged.

**Pull request closed without merging**
